#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="$SCRIPT_DIR:$PATH"

# build prompt from all args add put spaces in between, shift
prompt=""
while [ "$#" -gt 0 ]; do
    prompt="$prompt $1"
    shift
done

eval $(llm -p "$prompt" --type bash --instruction "I am using $SHELL")
